- hosts: all
  tasks:

   - yum:
       name: docker-ce
       state: present

   - copy:
       src: "/root/get-pip.py"
       dest: "/root/get-pip.py"

   - command: "python get-pip.py"

   - pip:
       name: docker
       state: latest


   - service:
       name: docker
       state: started

   - copy:
       src: "/root/jupyter_saas.tar"
       dest: "/root/jupyter_saas.tar"

   - docker_image:
       name: "jupyter:v3"
       load_path: "/root/jupyter_saas.tar"
       state: present

   - docker_container:
       name: "j1"
       image: "jupyter:v3"
       state: started
       interactive: true
       ipc_mode: host
       tty: true
       exposed_ports: 8888
       published_ports: "2400:8888"
       command: "jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root"
